### ISSUE TITLE
Missing fields in Android compared to iOS

### ISSUE THREAD

**Issue by bramley-stride** [ServicePattern/MobileAPI_Android#23]
Regarding https://github.com/ServicePattern/MobileAPI_IOS/issues/27, there are fields named `email, first_name, last_name` in the iOS SDK that aren't in the Android SDK.
There's a `phoneNumber` and `from` parameter, but it doesn't look like they're actually used in the method: https://github.com/ServicePattern/MobileAPI_Android/blob/1445990f4f2303dd1f45c4fee5026f67383261c6/BPContactCenter/src/main/java/com/brightpattern/bpcontactcenter/ContactCenterCommunicator.kt#L170

**Comment by ALobastov** [comment]
The signatures of the requestChat() method in both SDKs are actually exactly the same. The method takes two well defined arguments (phoneNumber and From) and one extra dictionary of optional parameters application may pass to the scenario (Parameters).

The only difference is in the sample applications. iOS app utilizes the Parameters dictionary to pass email and first/last names to the scenario. The Android sample app does not utilize the extra dictionary and just passes empty JSONObject here.

**Comment by bramley-stride** [comment]
But the ios sdk passes `phoneNumber` and `from` to `RequestChatParameters`: https://github.com/ServicePattern/MobileAPI_IOS/blob/b0acbc58dae852c50264b7b79fcbb3032ed88b10/BPMobileMessaging/Classes/ConactCenterCommunication/ContactCenterCommunicator.swift#L112-L114

Android SDK leaves these parameters unused, and POSTs the passed JSONObject instead. https://github.com/ServicePattern/MobileAPI_Android/blob/1445990f4f2303dd1f45c4fee5026f67383261c6/BPContactCenter/src/main/java/com/brightpattern/bpcontactcenter/ContactCenterCommunicator.kt#L170-L173

________________________________

**Comment by bramley-stride** [comment]
But the ios sdk passes `phoneNumber` and `from` to `RequestChatParameters`: 
https://github.com/ServicePattern/MobileAPI_IOS/blob/b0acbc58dae852c50264b7b79fcbb3032ed88b10/BPMobileMessaging/Classes/ConactCenterCommunication/ContactCenterCommunicator.swift#L112-L114

Android SDK leaves these parameters unused, and POSTs the passed JSONObject instead. https://github.com/ServicePattern/MobileAPI_Android/blob/1445990f4f2303dd1f45c4fee5026f67383261c6/BPContactCenter/src/main/java/com/brightpattern/bpcontactcenter/ContactCenterCommunicator.kt#L170-L173

**Comment by ALobastov** [comment]
Correct, the requestChat() signature has phoneNumber and From arguments but they are not sent to the server in REST request. Needs to be fixed.
