### ISSUE TITLE
Duplicate messages in chat events

### ISSUE THREAD

**Issue by bramley-stride** [ServicePattern/MobileAPI_Android#27]
Same as iOS issue: 
https://github.com/ServicePattern/MobileAPI_IOS/issues/31
Sometimes apps are getting duplicate events so duplicated messages in chat window. It's not happening every time.
![image](https://user-images.githubusercontent.com/38546721/114377126-a726c600-9bc9-11eb-9ffe-dd3092a8c205.png)
![image](https://user-images.githubusercontent.com/38546721/114377149-ad1ca700-9bc9-11eb-82a3-46bf6179be69.png)

**Comment by ALobastov** [comment]
Please close once same iOS issue is resolved (https://github.com/ServicePattern/MobileAPI_IOS/issues/31). 

Seems the server is fine, but the app uses async event polling and getChatHistory() concurrently and renders the events twice (one from polling and once from getChatHistory response).
