### ISSUE TITLE
50 messages received in rapid succession

### ISSUE THREAD

**Issue by bramley-stride** [ServicePattern/MobileAPI_Android#30]
Steps to reproduce:
1. open a new chat
2. get the prompt "If you know your case number, please enter it now. You may also reply New to open a new case."
3. Type New
4. Receive:
5. "Describe your issue please"
6. "case 1013 has been found: , status is New"
7. "There are no agents available to handle your request at this time. Please try again later." repeated 50 times rapidly, including via push notification. This is pretty distressing for the user, as their phone is constantly vibrating for several minutes with no way to stop it ☹️ 

Screenshots:
![image](https://user-images.githubusercontent.com/38546721/115141895-1c8b0e80-a082-11eb-8f5d-b55f362c7c98.png)

![image](https://user-images.githubusercontent.com/38546721/115141899-20b72c00-a082-11eb-8201-8e86e34d4dee.png)

![image](https://user-images.githubusercontent.com/38546721/115141904-257be000-a082-11eb-90f0-5e00f219158e.png)

I also can't de-dupe these messages via the logic in https://github.com/ServicePattern/MobileAPI_IOS/issues/31, because they do not have unique IDs.

**Comment by ALobastov** [comment]
Please, alsways attach client side logs (xCode, Android Studio debug logs) to all issues you open.

**Comment by bramley-stride** [comment]
Please find `logcat.txt` output from our app, and a list of `*_push_*.txt` payload logs. In this case, 102 push notifications were received in 4 seconds. https://slack-files.com/T02PJ7K9H-F01V43XE8LR-317090c180

The duplicate messages were received with `messageID` starting at 6, incrementing by 2 each time up to 204 for the last duplicate message. 

The push logs are generated by our app for all received push notifications, and include all payload fields.

**Comment by ALobastov** [comment]
Again - wrong scenario. It looks like there are no agents logged in at the time of testing. Therefor Find Agent scenario block exited to No Agent branch. Based on server log, scenario sends the "There are no agents available to handle your request at this time. Please try again later." message (which is correct), but then goes back to Find Agent block so the loop continues. This happens 100 times after which the server detects an infinite loop and terminates a scenario. 

If Find Agent scenario block exits to No Agents - there is absolutely no sense to keep queueing chat again and again.

Scenario should be corrected by TTec.
